const JobOrderData = [
  {
    ID: "0001",
    firstName: "Jessica",
    lastName: "Quintana Rivera",
    date: "01/01/2023",
    status: "New",
  },
  {
    ID: "0002",
    firstName: "Radahn",
    lastName: "Montreal Rivera",
    date: "02/01/2023",
    status: "Working",
  },
  {
    ID: "0003",
    firstName: "Hector Antonio",
    lastName: "Montalvo Alvarez",
    date: "02/11/2023",
    status: "Complete",
  },
  {
    ID: "0004",
    firstName: "Ismalito",
    lastName: "Acevedo Rivera",
    date: "02/12/2023",
    status: "Canceled",
  },
  {
    ID: "0005",
    firstName: "Ismalito",
    lastName: "Acevedo Rivera",
    date: "02/12/2023",
    status: "Canceled",
  },
  {
    ID: "0006",
    firstName: "Hector Antonio",
    lastName: "Montalvo Alvarez",
    date: "02/11/2023",
    status: "Complete",
  },
  {
    ID: "0007",
    firstName: "Hector Antonio",
    lastName: "Montalvo Alvarez",
    date: "02/11/2023",
    status: "Complete",
  },
  {
    ID: "0008",
    firstName: "Radahn",
    lastName: "Montreal Rivera",
    date: "02/01/2023",
    status: "Working",
  },
  {
    ID: "0009",
    firstName: "Jessica",
    lastName: "Quintana Rivera",
    date: "01/01/2023",
    status: "New",
  },
  {
    ID: "0010",
    firstName: "Radahn",
    lastName: "Montreal Rivera",
    date: "02/01/2023",
    status: "Working",
  },
  {
    ID: "0011",
    firstName: "Jessica",
    lastName: "Quintana Rivera",
    date: "01/01/2023",
    status: "New",
  },
  {
    ID: "0012",
    firstName: "Radahn",
    lastName: "Montreal Rivera",
    date: "02/01/2023",
    status: "Working",
  },
];

export default JobOrderData;
