const Clients = [
  {
    id: "0001",
    ClientFirstName: "Jessica",
    ClientLastName: "Quintana Rivera",
    JobOrderStatus: "New",
    JobOrderEntryDate: "09/07/2022",
    levelJobOrder: "Heavy",
  },
  {
    id: "0002",
    ClientFirstName: "Jan",
    ClientLastName: "Montalvo Medina",
    JobOrderStatus: "New",
    JobOrderEntryDate: "10/07/2022",
    levelJobOrder: "Heavy",
  },
  {
    id: "0003",
    ClientFirstName: "Jessica",
    ClientLastName: "Rivera Acevedo",
    JobOrderStatus: "New",
    JobOrderEntryDate: "11/07/2022",
    levelJobOrder: "Heavy",
  },
  {
    id: "0004",
    ClientFirstName: "Milagro",
    ClientLastName: "Acevedo Cardona",
    JobOrderStatus: "New",
    JobOrderEntryDate: "12/07/2022",
    levelJobOrder: "Heavy",
  },
  {
    id: "0005",
    ClientFirstName: "Stephanie",
    ClientLastName: "Quintana Rivera",
    JobOrderStatus: "New",
    JobOrderEntryDate: "13/07/2022",
    levelJobOrder: "Light",
  },
  {
    id: "0006",
    ClientFirstName: "Ismalito",
    ClientLastName: "Rivera Acevedo",
    JobOrderStatus: "New",
    JobOrderEntryDate: "14/07/2022",
    levelJobOrder: "Light",
  },
  {
    id: "0007",
    ClientFirstName: "Nereida",
    ClientLastName: "Acevedo Cardona",
    JobOrderStatus: "New",
    JobOrderEntryDate: "15/07/2022",
    levelJobOrder: "Light",
  },
];

export default Clients;
